CREATE TABLE plants (﻿id int, Common_name varchar(50), Scientific_name varchar(50), Family varchar(50), Origin varchar (50), Life_cycle varchar(50));
INSERT INTO plants VALUES ('1', 'giant reed', 'Arundo donax', 'Poaceae', ' shrub', ' recreational boating');
INSERT INTO plants VALUES ('2', 'mosquito fern', 'Azolla pinnata', 'Azollaceae', '"Oceania', 'freshwater');
INSERT INTO plants VALUES ('3', 'flowering rush', 'Butomus umbellatus', 'Butomaceae', 'Eurasia', 'freshwater');
INSERT INTO plants VALUES ('4', 'fanwort', 'Cabomba caroliniana', 'Cabombaceae', '"South America', ' Asia');
INSERT INTO plants VALUES ('5', 'pond water-starwort', 'Callitriche stagnalis', 'Plantaginaceae', 'Europe', ' wetland');
INSERT INTO plants VALUES ('6', '"lesser pond sedge', 'Carex acutiformis', '39477', 'graminoid', 'commercial shipping');
INSERT INTO plants VALUES ('7', 'killer algae', 'Caulerpa taxifolia (aquarium/Mediterranean strain)', 'Caulerpaceae', '"Oceania', ' recreational boating');
INSERT INTO plants VALUES ('8', '"Australian stonecrop', 'Crassula helmsii', '894364', 'forb/herb', '1300');
INSERT INTO plants VALUES ('9', 'cylindro (cyanobacteria)', 'Cylindrospermopsis raciborskii', 'Nostocaceae', 'South America', 'freshwater');
INSERT INTO plants VALUES ('10', '"didymo', 'Didymosphenia geminata', '591283', 'diatom', ' recreational boating"');
INSERT INTO plants VALUES ('11', 'Brazilian waterweed', 'Egeria densa', 'Hydrocharitaceae', 'South America', ' Asia');
INSERT INTO plants VALUES ('12', 'anchored water hyacinth', 'Eichhornia azurea', 'Pontederiaceae', '"South America', '"lake/pond');
INSERT INTO plants VALUES ('13', 'water hyacinth', 'Eichhornia crassipes', 'Pontederiaceae', 'South America', '1200');
INSERT INTO plants VALUES ('14', '"sea lettuce', 'Enteromoprha (Ulva) intestinalis', 'Plant', 'Ulvaceae', '1926');
INSERT INTO plants VALUES ('15', 'Japanese knotweed ', 'Fallopia japonica', 'Polygonaceae', 'Asia', 'freshwater');
INSERT INTO plants VALUES ('16', 'mudmat', 'Glossostigma cleistanthum', 'Scrophulariaceae', 'Oceania', ' river/stream');
INSERT INTO plants VALUES ('17', '"rough mannagrass', 'Glyceria maxima', '40846', 'graminoid', '2500');
INSERT INTO plants VALUES ('18', 'giant hogweed ', 'Heracleum mantegazzianum', 'Apiaceae', 'Asia', '6000');
INSERT INTO plants VALUES ('19', 'chameleon', 'Houttuynia cordata', 'Saururaceae', 'Asia', ' river/stream');
INSERT INTO plants VALUES ('20', 'hydrilla ', 'Hydrilla verticillata', 'Hydrocharitaceae', 'Asia', ' South America');
INSERT INTO plants VALUES ('21', 'European frogbit ', 'Hydrocharis morsus-ranae', 'Hydrocharitaceae', '"Eurasia', ' PQ');
INSERT INTO plants VALUES ('22', 'floating marsh pennywort', 'Hydrocotyle ranunculoides', 'Apiaceae', 'North America', ' river/stream');
INSERT INTO plants VALUES ('23', 'Indian swampweed', 'Hygrophila polysperma', 'Acanthaceae', 'Asia', 'freshwater');
INSERT INTO plants VALUES ('24', 'water spinach', 'Ipomoea aquatica', 'Convolvulaceae', ' vine"', 'freshwater');
INSERT INTO plants VALUES ('25', 'yellow flag iris', 'Iris pseudacorus', 'Iridaceae', 'Eurasia', ' canal"');
INSERT INTO plants VALUES ('26', '"oxygen weed', 'Lagarosiphon major', 'Plant', 'Hydrocharitaceae', ' canal"');
INSERT INTO plants VALUES ('27', 'dotted duckweed', 'Landoltia punctata', 'Lemnaceae', '"Asia', ' river/stream');
INSERT INTO plants VALUES ('28', '"sponge plant', 'Limnobium spongia', '38948', 'forb/herb', '"lake/pond');
INSERT INTO plants VALUES ('29', 'Asian marshweed', 'Limnophila sessiliflora', 'Plantaginaceae', 'Asia', '"lake/pond');
INSERT INTO plants VALUES ('30', 'purple loosestrife ', 'Lythrum salicaria', 'Lythraceae', '"Eurasia', 'Yes');
INSERT INTO plants VALUES ('31', 'wanded loosestrife', 'Lythrum virgatum', 'Lythraceae', 'Eurasia', '"wide range of habitats');
INSERT INTO plants VALUES ('32', '"water shamrock', 'Marsilea quadrifolia', '17995', 'forb/herb', '20 cm');
INSERT INTO plants VALUES ('33', '"melaleuca', 'Melaleuca quinquenervia', 'Plant', 'Myrtaceae', '"commercial shipping');
INSERT INTO plants VALUES ('34', 'amur silvergrass', 'Miscanthus sacchariflorus ', 'Poaceae', 'Asia', 'freshwater');
INSERT INTO plants VALUES ('35', '"Chinese silvergrass', 'Miscanthus sinensis ', '41874', 'graminoid', '"commercial shipping');
INSERT INTO plants VALUES ('36', '"arrowleaf false pickerelweed', 'Monochoria hastata', '503870', 'forb/herb', 'freshwater');
INSERT INTO plants VALUES ('37', 'heartshape false pickerelweed', 'Monochoria vaginalis', 'Pontederiaceae', 'Asia', ' river/stream');
INSERT INTO plants VALUES ('38', 'aquatic forget-me-not', 'Myosotis scorpioides', 'Boraginaceae', 'Eurasia', ' river/stream');
INSERT INTO plants VALUES ('39', '"parrot's feather', 'Myriophyllum aquaticum', '503904', 'forb/herb', ' OH');
INSERT INTO plants VALUES ('40', 'Eurasian watermilfoil', 'Myriophyllum spicatum', 'Haloragidaceae', '"Eurasia', ' commercial shipping"');
INSERT INTO plants VALUES ('41', '"spiny waternymph', 'Najas marina', '39001', 'forb/herb', ' Eurasia');
INSERT INTO plants VALUES ('42', '"brittle waternymph', 'Najas minor', '39002', 'forb/herb', '"aquarium/garden');
INSERT INTO plants VALUES ('43', 'watercress', 'Nasturtium officinale', 'Brassicaceae', '"Eurasia', ' recreational boating');
INSERT INTO plants VALUES ('44', 'sacred lotus', 'Nelumbo nucifera', 'Nelumbonaceae', '"Asia', '"lake/pond');
INSERT INTO plants VALUES ('45', 'starry stonewort', 'Nitellopsis obtusa', 'Characeae', 'Eurasia', ' PA');
INSERT INTO plants VALUES ('46', '"banana waterlily', 'Nymphaea mexicana', '18385', 'forb/herb', '150 cm');
INSERT INTO plants VALUES ('47', 'yellow floating heart', 'Nymphoides peltata', 'Menyanthaceae', 'Eurasia', ' Europe');
INSERT INTO plants VALUES ('48', 'Java waterdropwort; Vietnamese parsley', 'Oenanthe javanica', 'Apiaceae', '"Asia', '"wetland');
INSERT INTO plants VALUES ('49', 'duck lettuce', 'Ottelia alismoides', 'Hydrocharitaceae', '"Africa', '700');
INSERT INTO plants VALUES ('50', '"phantom dinoflagellate', 'Pfiesteria spp.', '553097', 'phytoplankton like', ' river/stream"');
INSERT INTO plants VALUES ('51', '"phragmites', 'Phragmites australis australis', '1053534', 'graminoid', '"commercial shipping');
INSERT INTO plants VALUES ('52', 'water lettuce', 'Pistia stratiotes', 'Arum', '"Africa', ' WI"');
INSERT INTO plants VALUES ('53', 'curly-leaf pondweed', 'Potamogeton crispus', 'Potamogetonaceae', '"Eurasia', ' ON (Georgian Bay-Severn River area)"');
INSERT INTO plants VALUES ('54', 'golden alga', 'Prymnesium parvum', 'Prymnesiaceae', '"unknown', ' canal');
INSERT INTO plants VALUES ('55', 'greater spearwort', 'Ranunculus lingua', 'Ranunculaceae', 'Eurasia', '"lake/pond');
INSERT INTO plants VALUES ('56', 'arrowhead ', 'Sagittaria sagittifolia', 'Alismataceae', 'Eurasia', '"lake/pond');
INSERT INTO plants VALUES ('57', '"giant salvinia', 'Salvinia auriculata', '18013', 'forb/herb', ' recreational boating');
INSERT INTO plants VALUES ('58', 'giant salvinia', 'Salvinia biloba (herzogii)', 'Salviniaceae', 'South America', ' river/stream');
INSERT INTO plants VALUES ('59', 'giant salvinia', 'Salvinia molesta', 'Salviniaceae', 'South America', ' recreational boating');
INSERT INTO plants VALUES ('60', 'wetland nightshade ', 'Solanum tampicense', 'Solanaceae', '"North America', ' canal"');
INSERT INTO plants VALUES ('61', 'bur reed', 'Sparganium glomeratum', 'Typhaceae', '"Eurasia', ' canal"');
INSERT INTO plants VALUES ('62', 'novel cyanobacteria (order stigonematales)', 'Stigonematales spp.', 'NA', '"unknown', '"lake/pond');
INSERT INTO plants VALUES ('63', 'water soldier', 'Stratiotes aloides', 'Hydrocharitaceae', 'Eurasia', ' recreational boating');
INSERT INTO plants VALUES ('64', 'water chestnut', 'Trapa natans', 'Trapaceae', '"Eurasia', ' PA');
INSERT INTO plants VALUES ('65', 'southern cattail', 'Typha domingensis', 'Typhaceae', '"North America', '"North America');
INSERT INTO plants VALUES ('66', 'graceful cattail', 'Typha laxmannii', 'Typhaceae', 'Eurasia', ' wetland');
INSERT INTO plants VALUES ('67', '"hybrid cattail', 'Typha x glauca (T. latifolia x T. angustifolia)', '42328', 'forb/herb', ' Europe"');
